name: Bug Report
description: File a bug report to help me improve the mod.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: mc-version
    attributes:
      label: Your Minecraft Version
      description: "Enter the version of Minecraft you're using."
      placeholder: "e.g. 1.21.11"
    validations:
      required: true

  - type: input
    id: loader
    attributes:
      label: Your Mod Loader
      description: "Enter the version of Mod Loader you're using."
      placeholder: "e.g. Fabric"
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: Your Mod Version
      description: "Enter the version of Mod you're using."
      placeholder: "e.g. 0.1.0-alpha.1"
    validations:
      required: true

    - type: input
    id: system
    attributes:
      label: Your System
      description: "Enter the system you're using."
      placeholder: "e.g. Windows 11"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Write out clear steps to reproduce the problem.
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Files
      description: Paste the content of `logs/latest.log` or `crash-reports/crash-*.txt` here. 
      render: shell
    validations:
      required: true
      
    - type: textarea
    id: mod-list
    attributes:
      label: Your Mod List
      description: List the mods you were using when this bug happened.
      render: shell
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (screenshots, etc.).
