name: build

on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: microsoft
          java-version: 21

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: find mod jar
        run: |
          JAR=$(find build/libs \
            -name "*.jar" \
            ! -name "*-sources.jar" \
            ! -name "*-dev.jar" \
            ! -name "*-javadoc.jar" \
            | head -n 1)

          echo "JAR=$JAR" >> $GITHUB_ENV
          echo "JAR_NAME=$(basename "$JAR" .jar)" >> $GITHUB_ENV

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JAR_NAME }}
          path: ${{ env.JAR }}
          if-no-files-found: error
